import {
  PDFDocument,
  StandardFonts,
  rgb,
} from "pdf-lib";

export interface PdfStudyExport {
  title: string;
  type: string;
  createdAt: string;
  updatedAt: string;

  objective: string;
  questions: string;
  research: string;
  application: string;
  prayer: string;
  notes: string;
}

export async function exportStudyToPdf(
  study: PdfStudyExport
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();

  const page = pdf.addPage();

  const { width, height } = page.getSize();

  const margin = 50;

  let y = height - margin;

  const titleFont = await pdf.embedFont(
    StandardFonts.HelveticaBold
  );

  const bodyFont = await pdf.embedFont(
    StandardFonts.Helvetica
  );

  page.drawText("JW Meeting Companion", {
    x: margin,
    y,
    size: 22,
    font: titleFont,
    color: rgb(0.12, 0.32, 0.72),
  });

  y -= 40;

  page.drawText(study.title, {
    x: margin,
    y,
    size: 18,
    font: titleFont,
  });

  y -= 22;

  page.drawText(study.type, {
    x: margin,
    y,
    size: 12,
    font: bodyFont,
  });

  y -= 30;

  page.drawText(`Created: ${study.createdAt}`, {
    x: margin,
    y,
    size: 10,
    font: bodyFont,
  });

  y -= 16;

  page.drawText(`Updated: ${study.updatedAt}`, {
    x: margin,
    y,
    size: 10,
    font: bodyFont,
  });

  y -= 30;

  const sections = [
    ["Objective", study.objective],
    ["Questions", study.questions],
    ["Research", study.research],
    ["Application", study.application],
    ["Prayer", study.prayer],
    ["Notes", study.notes],
  ] as const;

  for (const [heading, content] of sections) {
    page.drawText(heading, {
      x: margin,
      y,
      size: 14,
      font: titleFont,
    });

    y -= 18;

    page.drawText(content || "-", {
      x: margin,
      y,
      size: 11,
      font: bodyFont,
      maxWidth: width - margin * 2,
      lineHeight: 14,
    });

    y -= 60;
  }

  page.drawText("Generated by JW Meeting Companion", {
    x: margin,
    y: 30,
    size: 9,
    font: bodyFont,
    color: rgb(0.4, 0.4, 0.4),
  });

  return await pdf.save();
}